import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react"
import { auth } from "@/auth";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();

  return (
    <SessionProvider session={session}>

      <html
        lang="en"
        className={` ${inter.className} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">{children}</body>
      </html>

    </SessionProvider>

  );
}
